# -*- python -*-

Import('env')
import sys

files = [
	"AudioJitTests.cpp",
	"DSPJitTester.cpp",
	"UnitTests.cpp",
	]

libs = [
	env['common'],
	env['dspcore'],
	]

env.Program('tester', files, LIBS = libs)
