# -*- python -*-

Import('env')
import sys

files = [
	"AudioJitTests.cpp",
	"DSPJitTester.cpp",
	"UnitTests.cpp",
	]

libs = [
	env['common'],
	env['dspcore'],
	]

if sys.platform == 'darwin':
	frames = ['CoreFoundation']
else:
	frames = []

env.Program('tester', files, LIBS = libs, FRAMEWORKS = frames)
