# -*- python -*-

Import('env')

files = [
	"AudioJitTests.cpp",
	"DSPJitTester.cpp",
	"UnitTests.cpp",
	]

libs = [
	'dspcore', 'common',
	]

env.Program('#' + env['binary_dir'] + 'tester', files, LIBS = libs)
