# -*- python -*-

Import('env')
import os
import sys

out_contents =\
	'#define SCM_REV_STR "' + env['gitrev'] + '"\n' +\
	'#define SCM_DESC_STR "' + env['gitdesc'] + '"\n' +\
	'#define SCM_BRANCH_STR "' + env['gitbranch'] + '"\n' +\
	'#define SCM_IS_MASTER ' + ('1' if env['gitbranch'] == 'master' else '0') + '\n\n'

Execute(Delete('Src/scmrev.h'))
outfile = open('Src/scmrev.h', 'w')
outfile.write(out_contents)
outfile.close()

files = [
	'Src/ABI.cpp',
	'Src/BreakPoints.cpp',
	'Src/CDUtils.cpp',
	'Src/CPUDetect.cpp',
	'Src/ColorUtil.cpp',
	'Src/ConsoleListener.cpp',
	'Src/Crypto/aes_cbc.cpp',
	'Src/Crypto/aes_core.cpp',
	'Src/Crypto/bn.cpp',
	'Src/Crypto/ec.cpp',
	'Src/Crypto/md5.cpp',
	'Src/Crypto/sha1.cpp',
	'Src/FileSearch.cpp',
	'Src/FileUtil.cpp',
	'Src/Hash.cpp',
	'Src/IniFile.cpp',
	'Src/LogManager.cpp',
	'Src/MathUtil.cpp',
	'Src/MemArena.cpp',
	'Src/MemoryUtil.cpp',
	'Src/Misc.cpp',
	'Src/MsgHandler.cpp',
	'Src/NandPaths.cpp',
	'Src/SDCardUtil.cpp',
	'Src/StringUtil.cpp',
	'Src/SymbolDB.cpp',
	'Src/SysConf.cpp',
	'Src/Thread.cpp',
	'Src/Thunk.cpp',
	'Src/Timer.cpp',
	'Src/Version.cpp',
	'Src/VideoBackendBase.cpp',
	'Src/x64Analyzer.cpp',
	'Src/x64Emitter.cpp',
	]

if sys.platform == 'win32':
	files += ['Src/ExtendedTrace.cpp']
	files += ['Src/stdafx.cpp']

env['CPPPATH'] += ['Src']
env['LIBS'] += env.StaticLibrary('common', files)
