# Type stub for the embedded `dolphin.controller` module.
# Override emulated controller input. controller_id is 0-based.
# States are plain dicts; unset keys default (buttons off, sticks centered).
# Overrides apply on the next polled frame and auto-clear unless re-set.

from typing import Any, Dict, Optional

# GC pad dict keys: Left Right Down Up A B X Y Z L R Start (bool),
# StickX StickY CStickX CStickY TriggerLeft TriggerRight AnalogA AnalogB (0..255),
# Connected (bool).
def get_gc_buttons(controller_id: int) -> Dict[str, Any]: ...
# Input as the game receives it: the played-back DTM frame during movie playback, else the live pad.
def get_gc_buttons_display(controller_id: int) -> Dict[str, Any]: ...
def set_gc_buttons(controller_id: int, state: Dict[str, Any]) -> None: ...  # clears next frame
def set_gc_input_override(controller_id: int, state: Dict[str, Any]) -> None: ...  # persists until cleared
def clear_gc_input_override(controller_id: int) -> None: ...

# Wii remote button dict keys: Left Right Down Up A B Plus Minus One Two Home (bool).
def get_wii_buttons(controller_id: int) -> Dict[str, Any]: ...
def set_wii_buttons(controller_id: int, state: Dict[str, Any]) -> None: ...

# Point the IR camera; z defaults to -2 (meters from the sensor bar).
def set_wii_ircamera_transform(controller_id: int, x: float, y: float, z: float = -2.0,
                               pitch: float = 0.0, yaw: float = 0.0, roll: float = 0.0) -> None: ...

# Accelerometer dict keys: X Y Z (0..1023).
def get_wii_accelerometer(controller_id: int) -> Dict[str, int]: ...
def set_wii_accelerometer(controller_id: int, state: Dict[str, int]) -> None: ...

# MotionPlus dict keys: X Y Z (gyro), SlowX SlowY SlowZ (bool). None if no MotionPlus.
def get_wii_gyroscope(controller_id: int) -> Optional[Dict[str, Any]]: ...
def set_wii_gyroscope(controller_id: int, state: Dict[str, Any]) -> None: ...

# Nunchuk button dict keys: C Z (bool), StickX StickY (0..255).
def get_nunchuck_buttons(controller_id: int) -> Dict[str, Any]: ...
def get_nunchuck_buttons_raw(controller_id: int) -> Dict[str, Any]: ...  # without calibration applied
def set_nunchuck_buttons(controller_id: int, state: Dict[str, Any]) -> None: ...
def get_nunchuck_accelerometer(controller_id: int) -> Dict[str, int]: ...
def set_nunchuck_accelerometer(controller_id: int, state: Dict[str, int]) -> None: ...
