# Type stub for the embedded `dolphin.gui` module.
# Documents the retained-mode widget API. Colors are ARGB ints (0xAARRGGBB);
# alpha is honored on the overlay path (transparency) and as rgba() alpha in QSS.

from typing import List, Optional, Tuple

# --- immediate-mode overlay drawing (rendered in the game viewport) ---

def add_osd_message(message: str, duration_ms: int = 2000, color_argb: int = 0xFFFFFF30) -> None: ...
def clear_osd_messages() -> None: ...
def get_display_size() -> Tuple[float, float]: ...
def draw_line(a: Tuple[float, float], b: Tuple[float, float], color: int, thickness: float = 1) -> None: ...
def draw_rect(a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0, thickness: float = 1) -> None: ...
def draw_rect_filled(a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0) -> None: ...
def draw_quad(a, b, c, d, color: int, thickness: float = 1) -> None: ...
def draw_quad_filled(a, b, c, d, color: int) -> None: ...
def draw_triangle(a, b, c, color: int, thickness: float = 1) -> None: ...
def draw_triangle_filled(a, b, c, color: int) -> None: ...
def draw_circle(center: Tuple[float, float], radius: float, color: int, num_segments: Optional[int] = None, thickness: float = 1) -> None: ...
def draw_circle_filled(center: Tuple[float, float], radius: float, color: int, num_segments: Optional[int] = None) -> None: ...
def draw_text(pos: Tuple[float, float], color: int, text: str) -> None: ...
def draw_polyline(points: List[Tuple[float, float]], color: int, closed: bool = False, thickness: float = 1) -> None: ...
def draw_convex_poly_filled(points: List[Tuple[float, float]], color: int) -> None: ...

# --- retained-mode widgets ---
#
# Widgets are declared once at script start; their state is read every frame.
# Two container kinds:
#   gui.overlay(title) -> Overlay   ImGui panel drawn inside the game viewport.
#   gui.window(title)  -> Window    floating Qt OS window on the desktop.
# Styling is creation-time only. The overlay takes simplified bg_color/text_color
# (no QSS); the window takes full raw QSS via style= plus convenience colors.

class Button:
    @property
    def clicked(self) -> bool: ...  # True once per click; reading consumes it

class SliderFloat:
    value: float

class Text:
    def set(self, text: str) -> None: ...

class Checkbox:
    checked: bool

class InputText:
    value: str

class Overlay:
    """In-viewport ImGui panel. Per-widget bg_color/text_color only (no QSS)."""
    def button(self, label: str, *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Button: ...
    def slider_float(self, label: str, min: float = 0.0, max: float = 1.0, *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> SliderFloat: ...
    def text(self, text: str = "", *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Text: ...
    def checkbox(self, label: str, checked: bool = False, *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Checkbox: ...
    def input_text(self, label: str, initial: str = "", *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> InputText: ...

class Window:
    """Floating Qt OS window. Full QSS via style=; raw style wins over the
    generated color fragment on conflict."""
    def button(self, label: str, *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Button: ...
    def slider_float(self, label: str, min: float = 0.0, max: float = 1.0, *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> SliderFloat: ...
    def text(self, text: str = "", *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Text: ...
    def checkbox(self, label: str, checked: bool = False, *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Checkbox: ...
    def input_text(self, label: str, initial: str = "", *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> InputText: ...

def overlay(title: str, *, bg_color: Optional[int] = None, text_color: Optional[int] = None) -> Overlay: ...
def window(title: str, *, style: Optional[str] = None, bg_color: Optional[int] = None, text_color: Optional[int] = None) -> Window: ...
