# Type stub for the embedded `dolphin.memory` module.
# Reads/writes emulated MEM1/MEM2 by effective address. All ops raise
# ValueError if memory is not yet initialized (no game running).

def read_u8(addr: int) -> int: ...
def read_u16(addr: int) -> int: ...
def read_u32(addr: int) -> int: ...
def read_u64(addr: int) -> int: ...
def read_s8(addr: int) -> int: ...
def read_s16(addr: int) -> int: ...
def read_s32(addr: int) -> int: ...
def read_s64(addr: int) -> int: ...
def read_f32(addr: int) -> float: ...
def read_f64(addr: int) -> float: ...
def read_bytes(addr: int, size: int) -> bytearray: ...

def write_u8(addr: int, value: int) -> None: ...
def write_u16(addr: int, value: int) -> None: ...
def write_u32(addr: int, value: int) -> None: ...
def write_u64(addr: int, value: int) -> None: ...
def write_s8(addr: int, value: int) -> None: ...
def write_s16(addr: int, value: int) -> None: ...
def write_s32(addr: int, value: int) -> None: ...
def write_s64(addr: int, value: int) -> None: ...
def write_f32(addr: int, value: float) -> None: ...
def write_f64(addr: int, value: float) -> None: ...
def write_bytes(addr: int, data: bytearray) -> None: ...

def invalidate_icache(addr: int) -> None: ...  # flush JIT cache after patching code

# Memchecks fire the event.on_memorybreakpoint callback when hit.
def add_memcheck(addr: int) -> None: ...
def remove_memcheck(addr: int) -> None: ...
