# Type stub for the embedded `dolphin.savestate` module.
# Save/load emulator state. slot is 0..99; out-of-range raises ValueError.

def save_to_slot(slot: int) -> None: ...
def load_from_slot(slot: int) -> None: ...
def save_to_file(filename: str) -> None: ...
def load_from_file(filename: str) -> None: ...
def save_to_bytes() -> bytes: ...               # full state as an in-memory blob
def load_from_bytes(data: bytes) -> None: ...
