# -*- python -*- 

Import('env')
import sys

name = "Plugin_PadSimpleEvnt"

if not env['GLTEST']:
    print name + " Doesn't work without testgl"
    Return()

files = [
	"PadSimple.cpp",
	]
padeenv = env.Clone()

if padeenv['HAVE_WX']:
    files += [ 
#        "GUI/ConfigDlg.cpp",
        ]

padeenv.Append(LIBS = [ 'common' ])

padeenv.SharedLibrary(env['plugin_dir']+name, files)
