# -*- python -*- 
 
Import('env')
import sys

wmenv = env.Clone()
name = "Plugin_Wiimote"

files = [
        "Config.cpp",
        "DataReports.cpp",
        "EmuDefinitions.cpp",
        "EmuDynamics.cpp",
        "EmuMain.cpp",
        "EmuPad.cpp",
        "EmuSubroutines.cpp",
        "Encryption.cpp",
        "main.cpp",
        "Rumble.cpp",
	"UDPWiimote.cpp"
	]

if wmenv['HAVE_WX']:
    files += [
        "ConfigBasicDlg.cpp",
        "ConfigPadDlg.cpp",
        "ConfigRecordingDlg.cpp",
        "ConfigGamepad.cpp",
        "ConfigRecording.cpp",
        "FillReport.cpp",
        ]

libs = [ 'common', 'inputcommon', 'inputuicommon', 'SDL' ]

cxxflags = [ ]

if wmenv['HAVE_WIIUSE']:
	libs  += [ 'wiiuse' ]
	files += [ "wiimote_real.cpp" ]
	files += [ "ReadWiimote.cpp" ]
	cxxflags += ['-DHAVE_WIIUSE']

wmenv.Append(
	CXXFLAGS = cxxflags,
	LIBS = libs,
	)

wmenv.SharedLibrary(env['plugin_dir']+name, files)
