# -*- python -*- 
 
Import('env')
import sys

wiienv = env.Clone()
name = "Plugin_Wiimote-testing"

files = [
        "Config.cpp",
        "DataReports.cpp",
        "EmuDefinitions.cpp",
		"EmuDynamics.cpp",
        "EmuMain.cpp",
        "EmuPad.cpp",
        "EmuSubroutines.cpp",
        "Encryption.cpp",
        "main.cpp",
	]
if wiienv['HAVE_WX']:
    files += [
        "ConfigDlg.cpp",
		"ConfigGamepad.cpp",
        "ConfigRecording.cpp",
        "FillReport.cpp",
        ]

libs = [ 'common', 'inputcommon' ]


cxxflags = [ '-fPIC' ]

if wiienv['HAVE_WIIUSE']:
    libs  += [ 'wiiuse' ]
    files += [ "wiimote_real.cpp" ]
    files += [ "ReadWiimote.cpp" ]
    cxxflags += ['-DHAVE_WIIUSE']

if sys.platform == 'darwin':
    wiienv.Append(
    	CXXFLAGS = cxxflags,
    	LINKFLAGS = ['-framework' ,'IOBluetooth'],
    	LIBS = libs,
    	)
else:
    wiienv.Append(
    	CXXFLAGS = cxxflags,
		LIBS = libs,
	)


wiienv.SharedLibrary(env['plugin_dir']+name, files)
