# -*- python -*-

Import('env')
import os
import sys

name = os.sep + "Plugin_VideoOGL"

files = [
	'RasterFont.cpp',
	'Render.cpp',
	'TextureCache.cpp',
	'NativeVertexFormat.cpp',
	'PixelShaderCache.cpp',
	'VertexShaderCache.cpp',
	'TextureConverter.cpp',
	'VertexManager.cpp',
	'PostProcessing.cpp',
	'FramebufferManager.cpp',
	'main.cpp',
	'GLUtil.cpp'
	]

libs = [ 'videocommon', 'GLEW', 'SOIL', 'common' ]

if env['HAVE_WX']:
	libs += [ 'videouicommon' ]

env.SharedLibrary(env['plugin_dir'] + name, files, LIBS = env['LIBS'] + libs)
