# -*- python -*-

Import('env')
import os
import sys

files = [
	'RasterFont.cpp',
	'Render.cpp',
	'TextureCache.cpp',
	'NativeVertexFormat.cpp',
	'PixelShaderCache.cpp',
	'VertexShaderCache.cpp',
	'TextureConverter.cpp',
	'VertexManager.cpp',
	'PostProcessing.cpp',
	'FramebufferManager.cpp',
	'main.cpp',
	'GLUtil.cpp'
	]

env['LIBS'] += ['videocommon']

if env['HAVE_WX']:
	env['LIBS'] += [ 'videouicommon' ]

env['libvideo'] = env.StaticLibrary(env['local_libs'] + 'video', files)
