# -*- python -*- 

Import('env')
import sys

name = "Plugin_DSP_NULL.so"

files = [
        "DSPHandler.cpp",
        "MailHandler.cpp",
	"main.cpp",
	"Globals.cpp",
        "UCodes/UCode_AX.cpp",
	"UCodes/UCode_CARD.cpp",
	"UCodes/UCode_InitAudioSystem.cpp",
	"UCodes/UCode_Jac.cpp",
	"UCodes/UCode_ROM.cpp",
	"UCodes/UCodes.cpp",
	"UCodes/UCode_Zelda.cpp",
	]

dspenv = env.Clone()
if not dspenv['osx64']:
    dspenv.Append(
	CXXFLAGS = [ '-fPIC' ],
        LIBS = [ 'common' ],
	)
else:
    dspenv.Append(
	CXXFLAGS = [ '-fPIC','-arch', 'x86_64' ],
	LINKFLAGS = [ '-arch', 'x86_64' ],
        LIBS = [ 'common' ],
	)

dspenv.SharedLibrary('../../../../'+env['plugin_dir']+name, files)
