Import('env')

files = ["DSPHandler.cpp",
		 "MailHandler.cpp",
         "main.cpp",
		 "Config.cpp",
		 "Globals.cpp",
		 "PCHW/Mixer.cpp",
         "UCodes/UCode_AX.cpp",
         "UCodes/UCode_CARD.cpp",
         "UCodes/UCode_InitAudioSystem.cpp",
         "UCodes/UCode_Jac.cpp",
         "UCodes/UCode_ROM.cpp",
         "UCodes/UCodes.cpp",
         "UCodes/UCode_Zelda.cpp",
		 ]
env.SharedLibrary("../../../../Binary/linux/Plugins/dsphle.so", files, LIBS = ["common"])
