# -*- python -*-

Import('env')
import sys

name = "Plugin_WiimoteNew"
wiinewenv = env.Clone()

files = [
	  'WiimoteEmu/WiimoteEmu.cpp',
	  'WiimoteEmu/Attachment/Classic.cpp',
	  'WiimoteEmu/Attachment/Attachment.cpp',
	  'WiimoteEmu/Attachment/Nunchuk.cpp',
	  'WiimoteEmu/Attachment/Drums.cpp',
	  'WiimoteEmu/Attachment/Guitar.cpp',
	  'WiimoteEmu/EmuSubroutines.cpp',
	  'WiimoteEmu/Encryption.cpp',
	  'WiimoteEmu/Speaker.cpp',
	  'WiimoteNew.cpp',
	]

wiinewenv.Append(
	LIBS = [ 'inputplugincommon', 'inputcommon', 'common' ],
	)

if sys.platform == 'darwin':
	wiinewenv['FRAMEWORKS'] = ['CoreFoundation', 'System', 'Cocoa', 'IOKit' ]

wiinewenv.SharedLibrary(env['plugin_dir']+name, files)
