# -*- python -*-

Import('env')
import sys

name = "Plugin_GCPad"
padenv = env.Clone()

if not env['HAVE_SDL']:
    print name + " must have SDL to be build"
    Return()

files = [
	'Config.cpp',
	'GCPad.cpp',
	'Rumble.cpp',
	]
if padenv['HAVE_WX']:
    files += [
        'ConfigJoypad.cpp',
        'ConfigBox.cpp',
        ]

padenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common', 'inputcommon' ],
	)

padenv.SharedLibrary(env['plugin_dir']+name, files)
