# -*- python -*-

Import('env')

if not env['HAVE_WX']:
	Return()

files = [
	'ConfigDiag.cpp',
	'ConfigDiagBitmaps.cpp',
	'WXInputBase.cpp',
	]

env.StaticLibrary(env['local_libs'] + 'inputuicommon', files)
