# -*- python -*- 

Import('env')
import sys

name = "Plugin_nJoy_Testing"

if not env['HAVE_SDL']:
    print name + " must have SDL to be build"
    Return()

files = [
	'nJoy.cpp',
	]
	
if env['HAVE_WX']:
	files +=[ 'GUI/AboutBox.cpp',
		  'GUI/ConfigBox.cpp',
		]

padenv = env.Clone()
padenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common' ],
	)

padenv.SharedLibrary(env['plugin_dir']+name, files)
