# -*- python -*- 

Import('env')
import sys

name = "Plugin_nJoy_Testing"

files = [
	'nJoy.cpp',
	'GUI/AboutBox.cpp',
	'GUI/ConfigBox.cpp',
	]

padenv = env.Clone()
padenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common' ],
	)
if not env['osx64']:
    padenv.SharedLibrary(env['plugin_dir']+name, files)
