// Copyright 2009 Dolphin Emulator Project
// Licensed under GPLv2+
// Refer to the license.txt file included.

static const char *rating_5[] = {
"96 32 33 1",
"7 c #EBB027",
"  c None",
"< c #E6A619",
"6 c #F3BE3B",
"9 c #EBA722",
"= c #E4A30E",
"1 c #F6C53F",
"3 c #F4B615",
"> c #F2B300",
"0 c #DA8900",
"o c #FAD048",
"$ c #F8C71D",
"e c #D88600",
"# c #FDD445",
"8 c #E8A81F",
": c #F6BE00",
"w c #E4A50B",
"- c #F1C033",
"q c #E5A60E",
"* c #EFB42F",
"% c #F5BC09",
"r c #D27700",
"; c #FACC3B",
", c #F2B219",
"X c #F3C53A",
"O c #F8C940",
"4 c #F0AF22",
"5 c #E9AE1B",
"2 c #F6C025",
". c #F4C93D",
"+ c #F2C632",
"& c #F4BA27",
"@ c #FAD44D",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    .X       .X       .X       .X       .X                                                      ",
"    oO       oO       oO       oO       oO                                                      ",
" +@#$%&*= +@#$%&*= +@#$%&*= +@#$%&*= +@#$%&*=                                                   ",
"  -;:>,<   -;:>,<   -;:>,<   -;:>,<   -;:>,<                                                    ",
"   1234     1234     1234     1234     1234                                                     ",
"  567890   567890   567890   567890   567890                                                    ",
"  qw  er   qw  er   qw  er   qw  er   qw  er                                                    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

static const char *rating_4[] = {
"96 32 47 1",
"l c #D2D2D2",
"o c #E1E1E1",
"i c #EBB027",
"  c None",
"9 c #E6A619",
"u c #F3BE3B",
"3 c #DADADA",
"a c #EBA722",
": c #E4A30E",
"w c #F6C53F",
"# c #E2E2E2",
"r c #F4B615",
"7 c #F2B300",
"s c #DA8900",
"q c #DBDBDB",
"O c #FAD048",
"* c #F8C71D",
"@ c #E3E3E3",
"h c #D88600",
"& c #FDD445",
"p c #E8A81F",
"6 c #F6BE00",
"0 c #DCDCDC",
"g c #E4A50B",
"k c #D5D5D5",
", c #E4E4E4",
"4 c #F1C033",
"1 c #DDDDDD",
"f c #E5A60E",
"d c #D6D6D6",
"; c #EFB42F",
"= c #F5BC09",
"j c #D27700",
"5 c #FACC3B",
"8 c #F2B219",
"< c #DEDEDE",
"X c #F3C53A",
"+ c #F8C940",
"t c #F0AF22",
"y c #E9AE1B",
"e c #F6C025",
"2 c #DFDFDF",
". c #F4C93D",
"$ c #F2C632",
"- c #F4BA27",
"> c #E0E0E0",
"% c #FAD44D",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    .X       .X       .X       .X       oo                                                      ",
"    O+       O+       O+       O+       @#                                                      ",
" $%&*=-;: $%&*=-;: $%&*=-;: $%&*=-;: >,,<1223                                                   ",
"  456789   456789   456789   456789   2#031q                                                    ",
"   wert     wert     wert     wert     #21<                                                     ",
"  yuipas   yuipas   yuipas   yuipas   0o<01d                                                    ",
"  fg  hj   fg  hj   fg  hj   fg  hj   33  kl                                                    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

static const char *rating_3[] = {
"96 32 47 1",
"l c #D2D2D2",
"o c #E1E1E1",
"i c #EBB027",
"  c None",
"9 c #E6A619",
"u c #F3BE3B",
"3 c #DADADA",
"a c #EBA722",
": c #E4A30E",
"w c #F6C53F",
"# c #E2E2E2",
"r c #F4B615",
"7 c #F2B300",
"s c #DA8900",
"q c #DBDBDB",
"O c #FAD048",
"* c #F8C71D",
"@ c #E3E3E3",
"h c #D88600",
"& c #FDD445",
"p c #E8A81F",
"6 c #F6BE00",
"0 c #DCDCDC",
"g c #E4A50B",
"k c #D5D5D5",
", c #E4E4E4",
"4 c #F1C033",
"1 c #DDDDDD",
"f c #E5A60E",
"d c #D6D6D6",
"; c #EFB42F",
"= c #F5BC09",
"j c #D27700",
"5 c #FACC3B",
"8 c #F2B219",
"< c #DEDEDE",
"X c #F3C53A",
"+ c #F8C940",
"t c #F0AF22",
"y c #E9AE1B",
"e c #F6C025",
"2 c #DFDFDF",
". c #F4C93D",
"$ c #F2C632",
"- c #F4BA27",
"> c #E0E0E0",
"% c #FAD44D",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    .X       .X       .X       oo       oo                                                      ",
"    O+       O+       O+       @#       @#                                                      ",
" $%&*=-;: $%&*=-;: $%&*=-;: >,,<1223 >,,<1223                                                   ",
"  456789   456789   456789   2#031q   2#031q                                                    ",
"   wert     wert     wert     #21<     #21<                                                     ",
"  yuipas   yuipas   yuipas   0o<01d   0o<01d                                                    ",
"  fg  hj   fg  hj   fg  hj   33  kl   33  kl                                                    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

static const char *rating_2[] = {
"96 32 47 1",
"l c #D2D2D2",
"o c #E1E1E1",
"i c #EBB027",
"  c None",
"9 c #E6A619",
"u c #F3BE3B",
"3 c #DADADA",
"a c #EBA722",
": c #E4A30E",
"w c #F6C53F",
"# c #E2E2E2",
"r c #F4B615",
"7 c #F2B300",
"s c #DA8900",
"q c #DBDBDB",
"O c #FAD048",
"* c #F8C71D",
"@ c #E3E3E3",
"h c #D88600",
"& c #FDD445",
"p c #E8A81F",
"6 c #F6BE00",
"0 c #DCDCDC",
"g c #E4A50B",
"k c #D5D5D5",
", c #E4E4E4",
"4 c #F1C033",
"1 c #DDDDDD",
"f c #E5A60E",
"d c #D6D6D6",
"; c #EFB42F",
"= c #F5BC09",
"j c #D27700",
"5 c #FACC3B",
"8 c #F2B219",
"< c #DEDEDE",
"X c #F3C53A",
"+ c #F8C940",
"t c #F0AF22",
"y c #E9AE1B",
"e c #F6C025",
"2 c #DFDFDF",
". c #F4C93D",
"$ c #F2C632",
"- c #F4BA27",
"> c #E0E0E0",
"% c #FAD44D",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    .X       .X       oo       oo       oo                                                      ",
"    O+       O+       @#       @#       @#                                                      ",
" $%&*=-;: $%&*=-;: >,,<1223 >,,<1223 >,,<1223                                                   ",
"  456789   456789   2#031q   2#031q   2#031q                                                    ",
"   wert     wert     #21<     #21<     #21<                                                     ",
"  yuipas   yuipas   0o<01d   0o<01d   0o<01d                                                    ",
"  fg  hj   fg  hj   33  kl   33  kl   33  kl                                                    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

static const char *rating_1[] = {
"96 32 47 1",
"l c #D2D2D2",
"o c #E1E1E1",
"i c #EBB027",
"  c None",
"9 c #E6A619",
"u c #F3BE3B",
"3 c #DADADA",
"a c #EBA722",
": c #E4A30E",
"w c #F6C53F",
"# c #E2E2E2",
"r c #F4B615",
"7 c #F2B300",
"s c #DA8900",
"q c #DBDBDB",
"O c #FAD048",
"* c #F8C71D",
"@ c #E3E3E3",
"h c #D88600",
"& c #FDD445",
"p c #E8A81F",
"6 c #F6BE00",
"0 c #DCDCDC",
"g c #E4A50B",
"k c #D5D5D5",
", c #E4E4E4",
"4 c #F1C033",
"1 c #DDDDDD",
"f c #E5A60E",
"d c #D6D6D6",
"; c #EFB42F",
"= c #F5BC09",
"j c #D27700",
"5 c #FACC3B",
"8 c #F2B219",
"< c #DEDEDE",
"X c #F3C53A",
"+ c #F8C940",
"t c #F0AF22",
"y c #E9AE1B",
"e c #F6C025",
"2 c #DFDFDF",
". c #F4C93D",
"$ c #F2C632",
"- c #F4BA27",
"> c #E0E0E0",
"% c #FAD44D",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    .X       oo       oo       oo       oo                                                      ",
"    O+       @#       @#       @#       @#                                                      ",
" $%&*=-;: >,,<1223 >,,<1223 >,,<1223 >,,<1223                                                   ",
"  456789   2#031q   2#031q   2#031q   2#031q                                                    ",
"   wert     #21<     #21<     #21<     #21<                                                     ",
"  yuipas   0o<01d   0o<01d   0o<01d   0o<01d                                                    ",
"  fg  hj   33  kl   33  kl   33  kl   33  kl                                                    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};

static const char *rating_0[] = {
"96 32 15 1",
"; c #D2D2D2",
". c #E1E1E1",
"  c None",
"% c #DADADA",
"o c #E2E2E2",
"* c #DBDBDB",
"X c #E3E3E3",
"& c #DCDCDC",
"- c #D5D5D5",
"+ c #E4E4E4",
"# c #DDDDDD",
"= c #D6D6D6",
"@ c #DEDEDE",
"$ c #DFDFDF",
"O c #E0E0E0",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    ..       ..       ..       ..       ..                                                      ",
"    Xo       Xo       Xo       Xo       Xo                                                      ",
" O++@#$$% O++@#$$% O++@#$$% O++@#$$% O++@#$$%                                                   ",
"  $o&%#*   $o&%#*   $o&%#*   $o&%#*   $o&%#*                                                    ",
"   o$#@     o$#@     o$#@     o$#@     o$#@                                                     ",
"  &.@&#=   &.@&#=   &.@&#=   &.@&#=   &.@&#=                                                    ",
"  %%  -;   %%  -;   %%  -;   %%  -;   %%  -;                                                    ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
};
