Import('env')

files = ["BannerLoader.cpp", 
         "BannerLoaderGC.cpp", 
         "BannerLoaderWii.cpp",
         "Blob.cpp", 
         "FileHandlerARC.cpp",
         "Filesystem.cpp",
         "FileSystemGCWii.cpp",
         "VolumeCreator.cpp",
         "VolumeGC.cpp",
         "VolumeWiiCrypted.cpp",
         "AES/aes_cbc.c",
         "AES/aes_core.c",
        ]
env.StaticLibrary("discio", files, LIBS = ["common"])
