# -*- python -*-

Import('env')

files = [
	'BannerLoader.cpp',
	'BannerLoaderGC.cpp',
	'BannerLoaderWii.cpp',
	'Blob.cpp',
	'CompressedBlob.cpp',
	'DriveBlob.cpp',
	'DiscScrubber.cpp',
	'FileBlob.cpp',
	'FileHandlerARC.cpp',
	'Filesystem.cpp',
	'FileSystemGCWii.cpp',
	'VolumeCommon.cpp',
	'VolumeCreator.cpp',
	'VolumeDirectory.cpp',
	'VolumeGC.cpp',
	'VolumeWad.cpp',
	'VolumeWiiCrypted.cpp',
	'NANDContentLoader.cpp',
	'WiiWad.cpp',
	'AES/aes_cbc.c',
	'AES/aes_core.c',
	]
libs = [
	'common'
	]
env.StaticLibrary(env['local_libs'] + 'discio', files, LIBS = libs)
