# IN_LIST needs CMP0057; cmake -P defaults it to OLD.
cmake_minimum_required(VERSION 3.13)

if(NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "OUTPUT_DIR must be provided")
endif()

if(NOT DEFINED PYTHON_ZIP OR PYTHON_ZIP STREQUAL "")
  set(PYTHON_ZIP "python.zip")
endif()

set(PYTHON_EMBED_DIR "${OUTPUT_DIR}/python-embed")

set(EXCLUDED_STDLIB_DIRS
  __pycache__
  ensurepip
  idlelib
  site-packages
  test
  tkinter
  turtledemo
  venv
)

file(REMOVE_RECURSE "${PYTHON_EMBED_DIR}")
file(MAKE_DIRECTORY "${PYTHON_EMBED_DIR}")

if(DEFINED PYTHON_STDLIB AND EXISTS "${PYTHON_STDLIB}")
  file(GLOB PYTHON_STDLIB_ITEMS LIST_DIRECTORIES true RELATIVE "${PYTHON_STDLIB}" "${PYTHON_STDLIB}/*")
  set(PYTHON_STDLIB_ARCHIVE_ITEMS)

  foreach(PYTHON_STDLIB_ITEM IN LISTS PYTHON_STDLIB_ITEMS)
    set(PYTHON_STDLIB_ITEM_PATH "${PYTHON_STDLIB}/${PYTHON_STDLIB_ITEM}")

    if(IS_DIRECTORY "${PYTHON_STDLIB_ITEM_PATH}")
      if(PYTHON_STDLIB_ITEM IN_LIST EXCLUDED_STDLIB_DIRS)
        continue()
      endif()

      list(APPEND PYTHON_STDLIB_ARCHIVE_ITEMS "${PYTHON_STDLIB_ITEM}")
    elseif(NOT PYTHON_STDLIB_ITEM MATCHES "\\.py[co]$")
      list(APPEND PYTHON_STDLIB_ARCHIVE_ITEMS "${PYTHON_STDLIB_ITEM}")
    endif()
  endforeach()

  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E tar cf "${PYTHON_EMBED_DIR}/${PYTHON_ZIP}"
            --format=zip ${PYTHON_STDLIB_ARCHIVE_ITEMS}
    WORKING_DIRECTORY "${PYTHON_STDLIB}"
    RESULT_VARIABLE PYTHON_ZIP_RESULT
  )

  if(NOT PYTHON_ZIP_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to create ${PYTHON_ZIP}")
  endif()
endif()

if(DEFINED PYTHON_DLLS AND EXISTS "${PYTHON_DLLS}")
  file(GLOB PYTHON_EXTENSION_MODULES "${PYTHON_DLLS}/*.pyd")
  foreach(PYTHON_EXTENSION_MODULE IN LISTS PYTHON_EXTENSION_MODULES)
    get_filename_component(PYTHON_EXTENSION_MODULE_NAME "${PYTHON_EXTENSION_MODULE}" NAME)
    if(PYTHON_EXTENSION_MODULE_NAME MATCHES "^_test" OR
       PYTHON_EXTENSION_MODULE_NAME STREQUAL "_ctypes_test.pyd" OR
       PYTHON_EXTENSION_MODULE_NAME STREQUAL "_tkinter.pyd")
      continue()
    endif()

    file(COPY "${PYTHON_EXTENSION_MODULE}" DESTINATION "${PYTHON_EMBED_DIR}")
  endforeach()
endif()
