# -*- python -*- 

Import('env')
import sys

if sys.platform == 'darwin':
	output = "../../../../Binary/mac/Plugins/padsimple.so"
else:
	output = "../../../../Binary/linux/Plugins/padsimple.so"

files = [
	"PadSimple.cpp",
        "XInputBase.cpp",
	"GUI/ConfigDlg.cpp",
	]

padenv = env.Clone()
padenv.Append(LIBS = [ 'common' ])
padenv.SharedLibrary(output, files)
