Import('env')
import sys

if sys.platform == 'darwin':
	output = "../../../../Binary/mac/Plugins/padsimple.so"
else:
	output = "../../../../Binary/linux/Plugins/padsimple.so"

files = ["main.cpp",
		 ]
padenv=env.Copy(CXXFLAGS = " `pkg-config --cflags sdl`", LINKFLAGS = " `pkg-config --libs sdl`")
padenv.SharedLibrary(output, files, LIBS=["common"])
