# -*- python -*- 

Import('env')
import sys

if sys.platform == 'darwin':
	output = "../../../../Binary/mac/Plugins/Plugin_Wiimote.so"
else:
	output = "../../../../Binary/linux/Plugins/Plugin_Wiimote.so"

files = [
	"Wiimote.cpp",
	]

padenv = env.Clone()
padenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common' ],
	)
if not env['osx64']:
    padenv.SharedLibrary(output, files)
