# -*- python -*- 

Import('env')
import sys

name = "Plugin_Wiimote"

files = [
	"Wiimote.cpp",
	]

padenv = env.Clone()

if padenv['osx64']:
    padenv.Append(
        CXXFLAGS = [ '-arch', 'x86_64' ],
        LINKFLAGS = [ '-arch', 'x86_64' ],
        LIBS = [ 'common' ],
        )
else:
    padenv.Append(
        CXXFLAGS = [ '-fPIC' ],
        LIBS = [ 'common' ],
        )

padenv.SharedLibrary(env['plugin_dir']+name, files)
