Import('env')
import sys

if sys.platform == 'darwin':
	output = "../../../../Binary/mac/Plugins/Plugin_Wiimote.so"
else:
	output = "../../../../Binary/linux/Plugins/Plugin_Wiimote.so"

files = [
	"Wiimote_Test.cpp",
	]

padenv = env.Clone()
padenv.Append(
	CXXFLAGS = ' ' + ' '.join([
		'-fPIC', '`wx-config --cppflags`', '`pkg-config --cflags sdl`'
		]),
	LINKFLAGS = ' ' + ' '.join([
		'`wx-config --libs`', '`pkg-config --libs sdl`'
		])
	)
padenv.SharedLibrary(output, files, LIBS = [ "common" ])

