# -*- python -*-

Import('env')
import sys

files = [
	"ABI.cpp",
	"CDUtils.cpp",
	"ChunkFile.cpp",
	"ColorUtil.cpp",
	"ConsoleWindow.cpp",
	"CPUDetect.cpp",
	"DynamicLibrary.cpp",
	"ExtendedTrace.cpp",
	"FileSearch.cpp",
	"FileUtil.cpp",
	"Hash.cpp",
	"IniFile.cpp",
	"MappedFile.cpp",
	"MathUtil.cpp",
	"MemArena.cpp",
	"MemoryUtil.cpp",
	"Misc.cpp",
	"MsgHandler.cpp",
	"Plugin.cpp",
	"PluginDSP.cpp",
	"PluginWiimote.cpp",
	"PluginVideo.cpp",
	"PluginPAD.cpp",
	"StringUtil.cpp",
	"Thread.cpp",
	"Thunk.cpp",
	"Timer.cpp",
	"Thread.cpp",
	"WaveFile.cpp",
	"x64Emitter.cpp",
	"x64Analyzer.cpp",
	]

if sys.platform == 'win32':
	files += [ "stdafx.cpp" ]

env_common = env.Clone()
env_common.Append(CXXFLAGS = [ '-fPIC' ])
env_common.StaticLibrary("common", files)
