# -*- python -*-

Import('env')
import os
import sys
from SconsTests import utils

utils.GenerateRevFile(env['flavor'], Dir('#Source/Core/Common/Src').abspath +
    os.sep + 'svnrev_template.h', 'svnrev.h')

files = [
	"ABI.cpp",
	"BreakPoints.cpp",
	"CDUtils.cpp",
	"ColorUtil.cpp",
	"ConsoleListener.cpp",
	"CPUDetect.cpp",
	"DynamicLibrary.cpp",
	"FileSearch.cpp",
	"FileUtil.cpp",
	"Hash.cpp",
	"IniFile.cpp",
	"LogManager.cpp",
	"MathUtil.cpp",
	"MemArena.cpp",
	"MemoryUtil.cpp",
	"Misc.cpp",
	"MsgHandler.cpp",
	"OpenCL.cpp",
	"Plugin.cpp",
	"PluginDSP.cpp",
	"PluginWiimote.cpp",
	"PluginVideo.cpp",
	"SDCardUtil.cpp",
	"StringUtil.cpp",
	"SymbolDB.cpp",
	"SysConf.cpp",
	"Thread.cpp",
	"Thunk.cpp",
	"Timer.cpp",
	"Thread.cpp",
	"Version.cpp",
	"x64Emitter.cpp",
	"x64Analyzer.cpp",
	"Crypto/bn.cpp",
	"Crypto/ec.cpp",
	"Crypto/md5.cpp",
	"Crypto/sha1.cpp",
	]

if sys.platform == 'win32':
	files += [ "ExtendedTrace.cpp" ]
	files += [ "stdafx.cpp" ]

env.StaticLibrary(env['local_libs'] + "common", files)
env['CPPPATH'] += ['.']
