# -*- python -*-

Import('env')
import os
import sys

files = [
	'BPMemLoader.cpp',
	'Clipper.cpp',
	'CommandProcessor.cpp',
	'CPMemLoader.cpp',
	'DebugUtil.cpp',
	'EfbCopy.cpp',
	'EfbInterface.cpp',
	'GLUtil.cpp',
	'HwRasterizer.cpp',
	'main.cpp',
	'OpcodeDecoder.cpp',
	'PixelEngine.cpp',
	'Rasterizer.cpp',
	'RasterFont.cpp',
	'Renderer.cpp',
	'SetupUnit.cpp',
	'Statistics.cpp',
	'Tev.cpp',
	'TextureEncoder.cpp',
	'TextureSampler.cpp',
	'TransformUnit.cpp',
	'VertexLoader.cpp',
	'SWVideoConfig.cpp',
	'XFMemLoader.cpp',
	]

if env['HAVE_WX']:
	files += [ 'VideoConfigDialog.cpp' ]

if sys.platform == 'win32':
	files += [ 'Win32.cpp' ]

env.StaticLibrary(env['local_libs'] + 'plugin_videosoftware', files)
