# -*- python -*-

Import('env')
import os
import sys

files = [
	'BPMemLoader.cpp',
	'Clipper.cpp',
	'SWCommandProcessor.cpp',
	'CPMemLoader.cpp',
	'DebugUtil.cpp',
	'EfbCopy.cpp',
	'EfbInterface.cpp',
	'HwRasterizer.cpp',
	'SWmain.cpp',
	'OpcodeDecoder.cpp',
	'SWPixelEngine.cpp',
	'Rasterizer.cpp',
	'SWRenderer.cpp',
	'SetupUnit.cpp',
	'SWStatistics.cpp',
	'Tev.cpp',
	'TextureEncoder.cpp',
	'TextureSampler.cpp',
	'TransformUnit.cpp',
	'SWVertexLoader.cpp',
	'SWVideoConfig.cpp',
	'XFMemLoader.cpp',
	]

if env['HAVE_WX']:
	files += [ 'VideoConfigDialog.cpp' ]

if sys.platform == 'win32':
	files += [ 'Win32.cpp' ]

env['LIBS'] += env.StaticObject(files)
