# -*- python -*-

Import('env')
import os
import sys

name = os.sep + "Plugin_VideoSoftware"

files = [
	'BPMemLoader.cpp',
	'Clipper.cpp',
	'CommandProcessor.cpp',
	'CPMemLoader.cpp',
	'DebugUtil.cpp',
	'EfbCopy.cpp',
	'EfbInterface.cpp',
	'GLUtil.cpp',
	'HwRasterizer.cpp',
	'main.cpp',
	'OpcodeDecoder.cpp',
	'PixelEngine.cpp',
	'Rasterizer.cpp',
	'RasterFont.cpp',
	'Renderer.cpp',
	'SetupUnit.cpp',
	'Statistics.cpp',
	'Tev.cpp',
	'TextureEncoder.cpp',
	'TextureSampler.cpp',
	'TransformUnit.cpp',
	'VertexFormatConverter.cpp',
	'VertexLoader.cpp',
	'VideoConfig.cpp',
	'XFMemLoader.cpp',
	]

libs = [ 'videocommon', 'GLEW', 'SOIL', 'common' ]

if sys.platform == 'darwin' and not env['HAVE_WX']:
	files += [ 'cocoaGL.m' ]
elif sys.platform == 'win32':
	files += [ 'Win32.cpp' ]
	
env.SharedLibrary(env['plugin_dir'] + name, files, LIBS = env['LIBS'] + libs)
