/*
 * Module code.
 *
 * Generated by SIP 4.18.1
 */

#include "sipAPIsip_dolphin.h"

#line 28 "/usr/share/sip/PyQt5/QtCore/qobject.sip"
#include <qobject.h>
#line 12 "./sipsip_dolphincmodule.cpp"

/* Define the strings used by this module. */
const char sipStrings_sip_dolphin[] = {
    'I', 's', 'I', 'n', 'D', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', 'W', 'a', 'r', 'n', 'i', 'n', 'g', 'E', 'n', 'a', 'b', 'l', 'e', 'd', 0,
    'm', 'o', 'u', 's', 'e', 'D', 'o', 'u', 'b', 'l', 'e', 'C', 'l', 'i', 'c', 'k', 'E', 'v', 'e', 'n', 't', 0,
    'G', 'e', 't', 'R', 'e', 'n', 'd', 'e', 'r', 'W', 'i', 'n', 'd', 'o', 'w', 'S', 'i', 'z', 'e', 0,
    'U', 'p', 'd', 'a', 't', 'e', 'S', 't', 'a', 't', 'e', 'S', 'l', 'o', 't', 'M', 'e', 'n', 'u', 0,
    'f', 'o', 'c', 'u', 's', 'P', 'r', 'e', 'v', 'i', 'o', 'u', 's', 'C', 'h', 'i', 'l', 'd', 0,
    'f', 'o', 'c', 'u', 's', 'N', 'e', 'x', 't', 'P', 'r', 'e', 'v', 'C', 'h', 'i', 'l', 'd', 0,
    'B', 'r', 'o', 'w', 's', 'e', 'D', 'e', 'f', 'a', 'u', 'l', 't', 'G', 'a', 'm', 'e', 0,
    'S', 'c', 'r', 'e', 'e', 'n', 'S', 'h', 'o', 't', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'F', 'u', 'l', 'l', 'S', 'c', 'r', 'e', 'e', 'n', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 'S', 'u', 'b', 'W', 'i', 'n', 'd', 'o', 'w', 's', 0,
    'h', 'a', 's', 'H', 'e', 'i', 'g', 'h', 't', 'F', 'o', 'r', 'W', 'i', 'd', 't', 'h', 0,
    'm', 'o', 'u', 's', 'e', 'R', 'e', 'l', 'e', 'a', 's', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'i', 's', 'S', 'i', 'g', 'n', 'a', 'l', 'C', 'o', 'n', 'n', 'e', 'c', 't', 'e', 'd', 0,
    's', 'e', 'n', 'd', 'e', 'r', 'S', 'i', 'g', 'n', 'a', 'l', 'I', 'n', 'd', 'e', 'x', 0,
    'S', 'e', 't', 'P', 'r', 'e', 'f', 'e', 'r', 'r', 'e', 'd', 'V', 'i', 'e', 'w', 0,
    'G', 'e', 't', 'P', 'r', 'e', 'f', 'e', 'r', 'r', 'e', 'd', 'V', 'i', 'e', 'w', 0,
    'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', 'y', 'R', 'e', 'm', 'o', 'v', 'e', 'd', 0,
    'E', 'm', 'u', 'l', 'a', 't', 'i', 'o', 'n', 'S', 't', 'o', 'p', 'p', 'e', 'd', 0,
    'E', 'm', 'u', 'l', 'a', 't', 'i', 'o', 'n', 'S', 't', 'a', 'r', 't', 'e', 'd', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 'O', 'l', 'd', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'i', 'n', 'i', 't', 'i', 'a', 'l', 'i', 'z', 'e', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'u', 'p', 'd', 'a', 't', 'e', 'M', 'i', 'c', 'r', 'o', 'F', 'o', 'c', 'u', 's', 0,
    'c', 'o', 'n', 't', 'e', 'x', 't', 'M', 'e', 'n', 'u', 'E', 'v', 'e', 'n', 't', 0,
    'i', 'n', 'p', 'u', 't', 'M', 'e', 't', 'h', 'o', 'd', 'E', 'v', 'e', 'n', 't', 0,
    'i', 'n', 'p', 'u', 't', 'M', 'e', 't', 'h', 'o', 'd', 'Q', 'u', 'e', 'r', 'y', 0,
    'd', 'i', 's', 'c', 'o', 'n', 'n', 'e', 'c', 't', 'N', 'o', 't', 'i', 'f', 'y', 0,
    'G', 'e', 't', 'R', 'e', 'n', 'd', 'e', 'r', 'T', 'o', 'M', 'a', 'i', 'n', 0,
    'B', 'r', 'o', 'w', 's', 'e', 'A', 'p', 'p', 'l', 'o', 'a', 'd', 'e', 'r', 0,
    'G', 'e', 't', 'S', 'e', 'l', 'e', 'c', 't', 'e', 'd', 'G', 'a', 'm', 'e', 0,
    'S', 'e', 't', 't', 'i', 'n', 'g', 's', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'E', 'm', 'u', 'l', 'a', 't', 'i', 'o', 'n', 'P', 'a', 'u', 's', 'e', 'd', 0,
    'S', 'h', 'o', 'w', 'A', 'b', 'o', 'u', 't', 'D', 'i', 'a', 'l', 'o', 'g', 0,
    'S', 't', 'a', 't', 'e', 'S', 'a', 'v', 'e', 'O', 'l', 'd', 'e', 's', 't', 0,
    'S', 't', 'a', 't', 'e', 'S', 'a', 'v', 'e', 'S', 'l', 'o', 't', 'A', 't', 0,
    'S', 't', 'a', 't', 'e', 'L', 'o', 'a', 'd', 'S', 'l', 'o', 't', 'A', 't', 0,
    'i', 'n', 'i', 't', 'S', 't', 'y', 'l', 'e', 'O', 'p', 't', 'i', 'o', 'n', 0,
    'm', 'i', 'n', 'i', 'm', 'u', 'm', 'S', 'i', 'z', 'e', 'H', 'i', 'n', 't', 0,
    'm', 'o', 'u', 's', 'e', 'P', 'r', 'e', 's', 's', 'E', 'v', 'e', 'n', 't', 0,
    'k', 'e', 'y', 'R', 'e', 'l', 'e', 'a', 's', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'd', 'e', 'v', 'i', 'c', 'e', 'T', 'r', 'a', 'n', 's', 'f', 'o', 'r', 'm', 0,
    'i', 'n', 't', 'e', 'r', 'n', 'a', 'l', '_', 'f', 'o', 'r', 'm', 'a', 't', 0,
    'a', 's', 'p', 'e', 'c', 't', 'R', 'a', 't', 'i', 'o', 'M', 'o', 'd', 'e', 0,
    'G', 'e', 't', 'C', 'o', 'n', 'f', 'i', 'r', 'm', 'S', 't', 'o', 'p', 0,
    'S', 'e', 't', 'D', 'e', 'f', 'a', 'u', 'l', 't', 'G', 'a', 'm', 'e', 0,
    'G', 'e', 't', 'D', 'e', 'f', 'a', 'u', 'l', 't', 'G', 'a', 'm', 'e', 0,
    'S', 'e', 't', 't', 'i', 'n', 'g', 's', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', 'y', 'A', 'd', 'd', 'e', 'd', 0,
    'f', 'o', 'c', 'u', 's', 'N', 'e', 'x', 't', 'C', 'h', 'i', 'l', 'd', 0,
    'h', 'e', 'i', 'g', 'h', 't', 'F', 'o', 'r', 'W', 'i', 'd', 't', 'h', 0,
    'd', 'r', 'a', 'g', 'L', 'e', 'a', 'v', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'd', 'r', 'a', 'g', 'E', 'n', 't', 'e', 'r', 'E', 'v', 'e', 'n', 't', 0,
    'm', 'o', 'u', 's', 'e', 'M', 'o', 'v', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'G', 'e', 't', 'F', 'u', 'l', 'l', 'S', 'c', 'r', 'e', 'e', 'n', 0,
    'B', 'r', 'o', 'w', 's', 'e', 'W', 'i', 'i', 'N', 'A', 'N', 'D', 0,
    'B', 'r', 'o', 'w', 's', 'e', 'D', 'V', 'D', 'R', 'o', 'o', 't', 0,
    'S', 'e', 't', 'V', 'i', 'e', 'w', 'C', 'o', 'l', 'u', 'm', 'n', 0,
    'S', 't', 'a', 't', 'e', 'S', 'a', 'v', 'e', 'U', 'n', 'd', 'o', 0,
    'S', 't', 'a', 't', 'e', 'L', 'o', 'a', 'd', 'U', 'n', 'd', 'o', 0,
    'S', 't', 'a', 't', 'e', 'S', 'a', 'v', 'e', 'S', 'l', 'o', 't', 0,
    'S', 't', 'a', 't', 'e', 'L', 'o', 'a', 'd', 'S', 'l', 'o', 't', 0,
    'c', 'h', 'a', 'n', 'g', 'e', 'd', 'S', 'i', 'g', 'n', 'a', 'l', 0,
    's', 'h', 'a', 'r', 'e', 'd', 'P', 'a', 'i', 'n', 't', 'e', 'r', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    't', 'h', 'r', 'e', 's', 'h', 'o', 'l', 'd', 'T', 'i', 'm', 'e', 0,
    'd', 'r', 'a', 'g', 'M', 'o', 'v', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'k', 'e', 'y', 'P', 'r', 'e', 's', 's', 'E', 'v', 'e', 'n', 't', 0,
    'f', 'o', 'c', 'u', 's', 'O', 'u', 't', 'E', 'v', 'e', 'n', 't', 0,
    't', 'r', 'a', 'n', 's', 'f', 'o', 'r', 'm', 'M', 'o', 'd', 'e', 0,
    'G', 'e', 't', 'S', 't', 'a', 't', 'e', 'S', 'l', 'o', 't', 0,
    'S', 'e', 't', 'A', 'p', 'p', 'l', 'o', 'a', 'd', 'e', 'r', 0,
    'G', 'e', 't', 'A', 'p', 'p', 'l', 'o', 'a', 'd', 'e', 'r', 0,
    'G', 'a', 'm', 'e', 'S', 'e', 'l', 'e', 'c', 't', 'e', 'd', 0,
    'S', 'e', 't', 'T', 'a', 'b', 'l', 'e', 'V', 'i', 'e', 'w', 0,
    'P', 'a', 't', 'h', 's', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'P', 'a', 'u', 's', 'e', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'S', 'e', 't', 'S', 't', 'a', 't', 'e', 'S', 'l', 'o', 't', 0,
    'F', 'r', 'a', 'm', 'e', 'A', 'd', 'v', 'a', 'n', 'c', 'e', 0,
    's', 'o', 'u', 'r', 'c', 'e', 'R', 'e', 'g', 'i', 'o', 'n', 0,
    't', 'a', 'r', 'g', 'e', 't', 'O', 'f', 'f', 's', 'e', 't', 0,
    'm', 'i', 'd', 'L', 'i', 'n', 'e', 'W', 'i', 'd', 't', 'h', 0,
    'f', 'o', 'c', 'u', 's', 'I', 'n', 'E', 'v', 'e', 'n', 't', 0,
    'b', 'o', 'u', 'n', 'd', 'i', 'n', 'g', 'R', 'e', 'c', 't', 0,
    'S', 'e', 't', 'L', 'a', 's', 't', 'G', 'a', 'm', 'e', 0,
    'G', 'e', 't', 'L', 'a', 's', 't', 'G', 'a', 'm', 'e', 0,
    'G', 'e', 't', 'T', 'h', 'e', 'm', 'e', 'D', 'i', 'r', 0,
    'P', 'a', 't', 'h', 'R', 'e', 'm', 'o', 'v', 'e', 'd', 0,
    'S', 'e', 't', 'L', 'i', 's', 't', 'V', 'i', 'e', 'w', 0,
    'S', 't', 'o', 'p', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'P', 'l', 'a', 'y', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'O', 'p', 'e', 'n', 'P', 'r', 'e', 's', 's', 'e', 'd', 0,
    'i', 'n', 'i', 't', 'P', 'a', 'i', 'n', 't', 'e', 'r', 0,
    'n', 'a', 't', 'i', 'v', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'a', 'c', 't', 'i', 'o', 'n', 'E', 'v', 'e', 'n', 't', 0,
    'c', 'h', 'a', 'n', 'g', 'e', 'E', 'v', 'e', 'n', 't', 0,
    't', 'a', 'b', 'l', 'e', 't', 'E', 'v', 'e', 'n', 't', 0,
    'm', 'a', 't', 'c', 'h', 'P', 'o', 'l', 'i', 'c', 'y', 0,
    'r', 'e', 's', 'i', 'z', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'p', 'a', 'i', 'n', 't', 'E', 'n', 'g', 'i', 'n', 'e', 0,
    'c', 'u', 's', 't', 'o', 'm', 'E', 'v', 'e', 'n', 't', 0,
    'e', 'v', 'e', 'n', 't', 'F', 'i', 'l', 't', 'e', 'r', 0,
    's', 'i', 'p', '_', 'd', 'o', 'l', 'p', 'h', 'i', 'n', 0,
    'S', 'e', 't', 'W', 'i', 'i', 'N', 'A', 'N', 'D', 0,
    'G', 'e', 't', 'W', 'i', 'i', 'N', 'A', 'N', 'D', 0,
    'S', 'e', 't', 'D', 'V', 'D', 'R', 'o', 'o', 't', 0,
    'G', 'e', 't', 'D', 'V', 'D', 'R', 'o', 'o', 't', 0,
    'c', 'h', 'a', 'n', 'g', 'e', 'P', 'a', 'g', 'e', 0,
    'P', 'a', 't', 'h', 'D', 'i', 'a', 'l', 'o', 'g', 0,
    'S', 'c', 'r', 'e', 'e', 'n', 's', 'h', 'o', 't', 0,
    'F', 'u', 'l', 'l', 's', 'c', 'r', 'e', 'e', 'n', 0,
    'e', 'n', 't', 'e', 'r', 'E', 'v', 'e', 'n', 't', 0,
    'l', 'e', 'a', 'v', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'c', 'o', 'n', 's', 't', 'r', 'a', 'i', 'n', 't', 0,
    'c', 'l', 'o', 's', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'r', 'e', 'p', 'e', 'a', 't', 'T', 'i', 'm', 'e', 0,
    'w', 'h', 'e', 'e', 'l', 'E', 'v', 'e', 'n', 't', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 'S', 'p', 'a', 'n', 0,
    'p', 'a', 'i', 'n', 't', 'E', 'v', 'e', 'n', 't', 0,
    'g', 'e', 'n', 'M', 'i', 'p', 'M', 'a', 'p', 's', 0,
    's', 'e', 't', 'V', 'i', 's', 'i', 'b', 'l', 'e', 0,
    'R', 'e', 'm', 'o', 'v', 'e', 'P', 'a', 't', 'h', 0,
    'c', 'h', 'i', 'l', 'd', 'E', 'v', 'e', 'n', 't', 0,
    't', 'i', 'm', 'e', 'r', 'E', 'v', 'e', 'n', 't', 0,
    'P', 'a', 't', 'h', 'A', 'd', 'd', 'e', 'd', 0,
    'S', 'h', 'o', 'w', 'T', 'a', 'b', 'l', 'e', 0,
    'S', 't', 'a', 't', 'e', 'S', 'a', 'v', 'e', 0,
    'S', 't', 'a', 't', 'e', 'L', 'o', 'a', 'd', 0,
    'd', 'r', 'a', 'w', 'F', 'r', 'a', 'm', 'e', 0,
    'd', 'r', 'o', 'p', 'E', 'v', 'e', 'n', 't', 0,
    'h', 'i', 'd', 'e', 'E', 'v', 'e', 'n', 't', 0,
    's', 'h', 'o', 'w', 'E', 'v', 'e', 'n', 't', 0,
    'm', 'o', 'v', 'e', 'E', 'v', 'e', 'n', 't', 0,
    'o', 'p', 'e', 'r', 'a', 't', 'i', 'o', 'n', 0,
    'l', 'i', 'n', 'e', 'W', 'i', 'd', 't', 'h', 0,
    'd', 'i', 'r', 'e', 'c', 't', 'o', 'r', 'y', 0,
    'a', 'l', 'i', 'g', 'n', 'm', 'e', 'n', 't', 0,
    'r', 'e', 'c', 'e', 'i', 'v', 'e', 'r', 's', 0,
    'p', 'r', 'e', 'c', 'i', 's', 'i', 'o', 'n', 0,
    'S', 'e', 't', 'P', 'a', 't', 'h', 's', 0,
    'G', 'e', 't', 'P', 'a', 't', 'h', 's', 0,
    'S', 'e', 't', 't', 'i', 'n', 'g', 's', 0,
    'G', 'a', 'm', 'e', 'L', 'i', 's', 't', 0,
    'S', 'h', 'o', 'w', 'L', 'i', 's', 't', 0,
    's', 'h', 'o', 'r', 't', 'c', 'u', 't', 0,
    'u', 's', 'e', 'r', 'D', 'a', 't', 'a', 0,
    's', 'i', 'z', 'e', 'H', 'i', 'n', 't', 0,
    'f', 'i', 'l', 'l', 'R', 'u', 'l', 'e', 0,
    't', 'a', 'b', 'A', 'r', 'r', 'a', 'y', 0,
    't', 'a', 'b', 'S', 't', 'o', 'p', 's', 0,
    'n', 'a', 'm', 'e', 'T', 'y', 'p', 'e', 0,
    'p', 'o', 's', 'i', 't', 'i', 'o', 'n', 0,
    'p', 'r', 'o', 'p', 'e', 'r', 't', 'y', 0,
    'T', 'o', 'o', 'l', 'B', 'a', 'r', 0,
    'M', 'e', 'n', 'u', 'B', 'a', 'r', 0,
    'y', 'M', 'a', 'r', 'g', 'i', 'n', 0,
    'x', 'M', 'a', 'r', 'g', 'i', 'n', 0,
    'r', 'o', 'w', 'S', 'p', 'a', 'n', 0,
    'e', 'x', 'p', 'o', 's', 'e', 'd', 0,
    'b', 'u', 'f', 'f', 'e', 'r', 's', 0,
    's', 'o', 'u', 'r', 'c', 'e', 's', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 0,
    'q', 'u', 'a', 'l', 'i', 't', 'y', 0,
    'd', 'e', 'v', 'T', 'y', 'p', 'e', 0,
    'f', 'i', 'l', 't', 'e', 'r', 's', 0,
    'e', 'n', 'a', 'b', 'l', 'e', 'd', 0,
    'o', 'p', 't', 'i', 'o', 'n', 's', 0,
    'B', 'r', 'o', 'w', 's', 'e', 0,
    's', 'u', 'n', 'k', 'e', 'n', 0,
    'r', 'e', 'j', 'e', 'c', 't', 0,
    'l', 'a', 'y', 'e', 'r', 's', 0,
    's', 't', 'r', 'i', 'd', 'e', 0,
    'm', 'e', 't', 'r', 'i', 'c', 0,
    'w', 'i', 'n', 'd', 'o', 'w', 0,
    'c', 'r', 'e', 'a', 't', 'e', 0,
    'p', 'r', 'o', 'p', 'e', 'r', 0,
    's', 'e', 'n', 'd', 'e', 'r', 0,
    'v', 'a', 'l', 'u', 'e', '9', 0,
    'v', 'a', 'l', 'u', 'e', '8', 0,
    'v', 'a', 'l', 'u', 'e', '7', 0,
    'v', 'a', 'l', 'u', 'e', '6', 0,
    'v', 'a', 'l', 'u', 'e', '5', 0,
    'v', 'a', 'l', 'u', 'e', '4', 0,
    'v', 'a', 'l', 'u', 'e', '3', 0,
    'v', 'a', 'l', 'u', 'e', '2', 0,
    'v', 'a', 'l', 'u', 'e', '1', 0,
    'v', 'a', 'l', 'u', 'e', '0', 0,
    's', 'y', 's', 't', 'e', 'm', 0,
    's', 'y', 'm', 'b', 'o', 'l', 0,
    's', 'u', 'f', 'f', 'i', 'x', 0,
    'o', 'f', 'f', 's', 'e', 't', 0,
    'p', 'r', 'e', 'f', 'i', 'x', 0,
    'f', 'i', 'l', 't', 'e', 'r', 0,
    'a', 'c', 'c', 'e', 'p', 't', 0,
    'o', 'p', 't', 'i', 'o', 'n', 0,
    'l', 'o', 'c', 'a', 'l', 'e', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 0,
    'o', 'b', 'j', 'e', 'c', 't', 0,
    'p', 'a', 'r', 'e', 'n', 't', 0,
    'P', 'a', 'u', 's', 'e', 0,
    'R', 'e', 's', 'e', 't', 0,
    'b', 'r', 'u', 's', 'h', 0,
    't', 'y', 'p', 'e', 's', 0,
    'e', 'x', 'e', 'c', '_', 0,
    'o', 'r', 'd', 'e', 'r', 0,
    'r', 'o', 'l', 'e', 's', 0,
    'f', 'l', 'a', 'g', 's', 0,
    'e', 'v', 'e', 'n', 't', 0,
    'm', 's', 'e', 'c', 's', 0,
    's', 't', 'a', 't', 'e', 0,
    'P', 'l', 'a', 'y', 0,
    'E', 'x', 'i', 't', 0,
    'd', 'o', 'n', 'e', 0,
    'O', 'p', 'e', 'n', 0,
    'e', 'x', 'e', 'c', 0,
    'm', 'o', 'd', 'e', 0,
    'n', 'a', 'm', 'e', 0,
    'b', 'a', 's', 'e', 0,
    'o', 'p', 'e', 'n', 0,
    'f', 'i', 'l', 'l', 0,
    'f', 'r', 'o', 'm', 0,
    's', 'o', 'r', 't', 0,
    'p', 'o', 's', 0,
    's', 'w', 0,
    's', 'y', 0,
    's', 'x', 0,
};


/*
 * This defines each type in this module.
 */
static sipTypeDef *typesTable[] = {
    &sipTypeDef_sip_dolphin_GameList.super.ctd_base,
    &sipTypeDef_sip_dolphin_MenuBar.super.ctd_base,
    &sipTypeDef_sip_dolphin_PathDialog.super.ctd_base,
    &sipTypeDef_sip_dolphin_Settings.super.ctd_base,
    &sipTypeDef_sip_dolphin_SettingsWindow.super.ctd_base,
    &sipTypeDef_sip_dolphin_ToolBar.super.ctd_base,
};


/* This defines the modules that this module needs to import. */
static sipImportedModuleDef importsTable[] = {
    {"PyQt5.QtCore", 1, NULL},
    {"PyQt5.QtGui", -1, NULL},
    {"PyQt5.QtWidgets", -1, NULL},
    {NULL, -1, NULL}
};


/* This defines this module. */
sipExportedModuleDef sipModuleAPI_sip_dolphin = {
    0,
    SIP_API_MINOR_NR,
    sipNameNr_sip_dolphin,
    0,
    -1,
    sipStrings_sip_dolphin,
    importsTable,
    NULL,
    6,
    typesTable,
    NULL,
    0,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};


/* The SIP API and the APIs of any imported modules. */
const sipAPIDef *sipAPI_sip_dolphin;
const sipExportedModuleDef *sipModuleAPI_sip_dolphin_QtCore;
const sipExportedModuleDef *sipModuleAPI_sip_dolphin_QtGui;
const sipExportedModuleDef *sipModuleAPI_sip_dolphin_QtWidgets;

sip_qt_metaobject_func sip_sip_dolphin_qt_metaobject;
sip_qt_metacall_func sip_sip_dolphin_qt_metacall;
sip_qt_metacast_func sip_sip_dolphin_qt_metacast;


/* The Python module initialisation function. */
#if PY_MAJOR_VERSION >= 3
#define SIP_MODULE_ENTRY        PyInit_sip_dolphin
#define SIP_MODULE_TYPE         PyObject *
#define SIP_MODULE_DISCARD(r)   Py_DECREF(r)
#define SIP_MODULE_RETURN(r)    return (r)
#else
#define SIP_MODULE_ENTRY        initsip_dolphin
#define SIP_MODULE_TYPE         void
#define SIP_MODULE_DISCARD(r)
#define SIP_MODULE_RETURN(r)    return
#endif

#if defined(SIP_STATIC_MODULE)
extern "C" SIP_MODULE_TYPE SIP_MODULE_ENTRY()
#else
PyMODINIT_FUNC SIP_MODULE_ENTRY()
#endif
{
    static PyMethodDef sip_methods[] = {
        {0, 0, 0, 0}
    };

#if PY_MAJOR_VERSION >= 3
    static PyModuleDef sip_module_def = {
        PyModuleDef_HEAD_INIT,
        "sip_dolphin",
        NULL,
        -1,
        sip_methods,
        NULL,
        NULL,
        NULL,
        NULL
    };
#endif

    PyObject *sipModule, *sipModuleDict;
    PyObject *sip_sipmod, *sip_capiobj;

    /* Initialise the module and get it's dictionary. */
#if PY_MAJOR_VERSION >= 3
    sipModule = PyModule_Create(&sip_module_def);
#elif PY_VERSION_HEX >= 0x02050000
    sipModule = Py_InitModule(sipName_sip_dolphin, sip_methods);
#else
    sipModule = Py_InitModule(const_cast<char *>(sipName_sip_dolphin), sip_methods);
#endif

    if (sipModule == NULL)
        SIP_MODULE_RETURN(NULL);

    sipModuleDict = PyModule_GetDict(sipModule);

    /* Get the SIP module's API. */
#if PY_VERSION_HEX >= 0x02050000
    sip_sipmod = PyImport_ImportModule(SIP_MODULE_NAME);
#else
    sip_sipmod = PyImport_ImportModule(const_cast<char *>(SIP_MODULE_NAME));
#endif

    if (sip_sipmod == NULL)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }

    sip_capiobj = PyDict_GetItemString(PyModule_GetDict(sip_sipmod), "_C_API");
    Py_DECREF(sip_sipmod);

#if defined(SIP_USE_PYCAPSULE)
    if (sip_capiobj == NULL || !PyCapsule_CheckExact(sip_capiobj))
#else
    if (sip_capiobj == NULL || !PyCObject_Check(sip_capiobj))
#endif
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }

#if defined(SIP_USE_PYCAPSULE)
    sipAPI_sip_dolphin = reinterpret_cast<const sipAPIDef *>(PyCapsule_GetPointer(sip_capiobj, SIP_MODULE_NAME "._C_API"));
#else
    sipAPI_sip_dolphin = reinterpret_cast<const sipAPIDef *>(PyCObject_AsVoidPtr(sip_capiobj));
#endif

#if defined(SIP_USE_PYCAPSULE)
    if (sipAPI_sip_dolphin == NULL)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }
#endif

    /* Export the module and publish it's API. */
    if (sipExportModule(&sipModuleAPI_sip_dolphin,SIP_API_MAJOR_NR,SIP_API_MINOR_NR,0) < 0)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(0);
    }

    sip_sip_dolphin_qt_metaobject = (sip_qt_metaobject_func)sipImportSymbol("qtcore_qt_metaobject");
    sip_sip_dolphin_qt_metacall = (sip_qt_metacall_func)sipImportSymbol("qtcore_qt_metacall");
    sip_sip_dolphin_qt_metacast = (sip_qt_metacast_func)sipImportSymbol("qtcore_qt_metacast");

    if (!sip_sip_dolphin_qt_metacast)
        Py_FatalError("Unable to import qtcore_qt_metacast");

    /* Initialise the module now all its dependencies have been set up. */
    if (sipInitModule(&sipModuleAPI_sip_dolphin,sipModuleDict) < 0)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(0);
    }

    /* Get the APIs of the modules that this one is dependent on. */
    sipModuleAPI_sip_dolphin_QtCore = sipModuleAPI_sip_dolphin.em_imports[0].im_module;
    sipModuleAPI_sip_dolphin_QtGui = sipModuleAPI_sip_dolphin.em_imports[1].im_module;
    sipModuleAPI_sip_dolphin_QtWidgets = sipModuleAPI_sip_dolphin.em_imports[2].im_module;

    SIP_MODULE_RETURN(sipModule);
}
