/* Generated by Cython 0.24.1 */

#ifndef __PYX_HAVE__wrap_dolphin
#define __PYX_HAVE__wrap_dolphin


#ifndef __PYX_HAVE_API__wrap_dolphin

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) cy_Host_Message(int);
__PYX_EXTERN_C DL_IMPORT(void) cy_Host_UpdateTitle(std::string const &);
__PYX_EXTERN_C DL_IMPORT(void) *cy_Host_GetRenderHandle(void);
__PYX_EXTERN_C DL_IMPORT(bool) cy_Host_RendererHasFocus(void);
__PYX_EXTERN_C DL_IMPORT(bool) cy_Host_RendererIsFullscreen(void);
__PYX_EXTERN_C DL_IMPORT(bool) cy_Host_UIHasFocus(void);

#endif /* !__PYX_HAVE_API__wrap_dolphin */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initwrap_dolphin(void);
#else
PyMODINIT_FUNC PyInit_wrap_dolphin(void);
#endif

#endif /* !__PYX_HAVE__wrap_dolphin */
