# -*- python -*- 

Import('env')
import sys

if sys.platform == 'darwin':
	output = '../../../../Binary/mac/Plugins/Plugin_nJoy_SDL.so'
else:
	output = '../../../../Binary/linux/Plugins/Plugin_nJoy_SDL.so'

files = [
	'nJoy.cpp',
	]
if not env['nowx']:
	files += ['GUI/AboutBox.cpp', 'GUI/ConfigBox.cpp',]

padenv = env.Clone()
padenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common' ],
	)
padenv.SharedLibrary(output, files)
