Import('env')
import sys

if sys.platform == 'darwin':
	output = "../../../../Binary/mac/Plugins/Plugin_nJoy_SDL.so"
else:
	output = "../../../../Binary/linux/Plugins/Plugin_nJoy_SDL.so"

files = [
	"nJoy.cpp",
	"GUI/AboutBox.cpp",
	"GUI/ConfigBox.cpp",
	]

padenv = env.Clone()
padenv.Append(
	CXXFLAGS = ' ' + ' '.join([
		'-fPIC', env['WXCPPFLAGS'], '`pkg-config --cflags sdl`'
		]),
	LINKFLAGS = ' ' + ' '.join([
		env['WXLIBFLAGS'], '`pkg-config --libs sdl`'
		])
	)
padenv.SharedLibrary(output, files, LIBS = [ "common" ])
