# -*- python -*-

Import('env')
import os
import sys

name = os.sep + "Plugin_VideoMerge"

files = [
	'BPFunctions.cpp',
	'FramebufferManager.cpp',
	'Main.cpp',
	'PixelShaderCache.cpp',
	'Renderer.cpp',
	'TextureCache.cpp',
	'VertexManager.cpp',
	'VertexShaderCache.cpp',
	'VideoConfigDiag.cpp',
	'OGL/OGL_FramebufferManager.cpp',
	'OGL/OGL_GLUtil.cpp',
	'OGL/OGL_NativeVertexFormat.cpp',
	'OGL/OGL_PixelShaderCache.cpp',
	'OGL/OGL_PostProcessing.cpp',
	'OGL/OGL_RasterFont.cpp',
	'OGL/OGL_Render.cpp',
	'OGL/OGL_TextureCache.cpp',
	'OGL/OGL_TextureConverter.cpp',
	'OGL/OGL_VertexManager.cpp',
	'OGL/OGL_VertexShaderCache.cpp',
	'OGL/OGL_XFB.cpp',
	]

if sys.platform == 'win32': files += [
	'EmuWindow.cpp',
	'DX11/DX11_D3DBase.cpp',
	'DX11/DX11_D3DBlob.cpp',
	'DX11/DX11_D3DShader.cpp',
	'DX11/DX11_D3DTexture.cpp',
	'DX11/DX11_D3DUtil.cpp',
	'DX11/DX11_FramebufferManager.cpp',
	'DX11/DX11_GfxState.cpp',
	'DX11/DX11_NativeVertexFormat.cpp',
	'DX11/DX11_PixelShaderCache.cpp',
	'DX11/DX11_Render.cpp',
	'DX11/DX11_TextureCache.cpp',
	'DX11/DX11_VertexManager.cpp',
	'DX11/DX11_VertexShaderCache.cpp',
	'DX9/DX9_D3DBase.cpp',
	'DX9/DX9_D3DShader.cpp',
	'DX9/DX9_D3DTexture.cpp',
	'DX9/DX9_D3DUtil.cpp',
	'DX9/DX9_FramebufferManager.cpp',
	'DX9/DX9_NativeVertexFormat.cpp',
	'DX9/DX9_PixelShaderCache.cpp',
	'DX9/DX9_Render.cpp',
	'DX9/DX9_TextureCache.cpp',
	'DX9/DX9_TextureConverter.cpp',
	'DX9/DX9_VertexManager.cpp',
	'DX9/DX9_VertexShaderCache.cpp',
	]

libs = [ 'videocommon', 'GLEW', 'SOIL', 'common' ]

env.SharedLibrary(env['plugin_dir'] + name, files, LIBS = env['LIBS'] + libs)
