# -*- python -*-

Import('env')
import sys

files = [
	"ir.cpp",
	"wiiuse.cpp",
	]

if sys.platform == 'darwin':
	files += [ "io_osx.m" ]
elif sys.platform == 'linux2' and env['HAVE_BLUEZ']:
	files += [ "io_nix.cpp" ]
elif sys.platform == 'win32':
	files += [ "io_win.cpp" ]
else:
	files += [ "io_dummy.cpp" ]

env.StaticLibrary(env['local_libs'] + "wiiuse", files)
env['CPPPATH'] += ['#Source/Core/wiiuse/Src']
