# -*- python -*-

Import('env')
if env['HAVE_WX']:
	
	files = [
		'ConfigDiagBitmaps.cpp',
		'ConfigDiag.cpp',
		'WXInputBase.cpp'
		]

	env_inputpc = env.Clone()
	env_inputpc.StaticLibrary(env['local_libs'] + "inputuicommon", files)
