# -*- python -*-
import sys
Import('env')

files = [
	'Configuration.cpp',
	'ControllerEmu.cpp',
	'InputConfig.cpp',
	'SDL_Util.cpp',
	'ControllerInterface/ControllerInterface.cpp',
	'ControllerInterface/SDL/SDL.cpp'
	]


if sys.platform == 'win32':
	files += [
		]
elif sys.platform == 'darwin':
	files += [
		'ControllerInterface/OSX/OSX.mm',
		'ControllerInterface/OSX/OSXKeyboard.mm',
		'ControllerInterface/OSX/OSXMouse.mm'
		]
else:
	files += [
		'ControllerInterface/Xlib/Xlib.cpp',
		'X11InputBase.cpp'
		]

env.StaticLibrary(env['local_libs'] + "inputcommon", files)
