# -*- python -*-
import sys
Import('env')

files = [
	'Configuration.cpp',
	'ControllerEmu.cpp',
	'EventHandler.cpp',
	'InputCommon.cpp',
	'InputConfig.cpp',
	'SDL_Util.cpp',
	'ControllerInterface/ControllerInterface.cpp',
	'ControllerInterface/SDL/SDL.cpp'
	]

if env['HAVE_X11']:
	files += [
		"X11InputBase.cpp",
		]

if env['HAVE_WX']:
	files += [
		"WXInputBase.cpp",
		]

if sys.platform == 'darwin':
	files += [
		'ControllerInterface/OSX/OSX.mm',
		'ControllerInterface/OSX/OSXKeyboard.mm',
		'ControllerInterface/OSX/OSXMouse.mm'
		]
		   
if sys.platform == 'linux2':
	files += [
		'ControllerInterface/Xlib/Xlib.cpp'
		]

env.StaticLibrary(env['local_libs'] + "inputcommon", files)
