# -*- python -*- 

Import('env')
import sys

if sys.platform == 'darwin':
	output = "../../../../Binary/mac/Plugins/dsplle.so"
else:
	output = "../../../../Binary/linux/Plugins/dsplle.so"

files = [
	"AOSoundStream.cpp",
	"disassemble.cpp",
	"gdsp_aram.cpp",
	"gdsp_ext_op.cpp",
	"gdsp_interface.cpp",
	"gdsp_interpreter.cpp",
	"gdsp_memory.cpp",
	"gdsp_opcodes.cpp",
	"gdsp_registers.cpp",
	"Globals.cpp",
	"opcodes.cpp",
	"Tools.cpp",
	"main.cpp",
        "Mixer.cpp",
        "Logging/ReadPBs.cpp",
        "Logging/Console.cpp",
        "Logging/Logging.cpp",
        "Logging/AXTask.cpp",
	]

lleenv = env.Clone()
lleenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common' ],
	)
lleenv.SharedLibrary(output, files)
