Import('env')

files = ["LogWindow.cpp", 
         "BreakPointDlg.cpp",
         "BreakpointView.cpp",
         "CodeView.cpp",
         "BreakpointWindow.cpp",
         "CodeWindow.cpp",
         "CodeView.cpp",
         "Debugger.cpp", 
         "MemoryCheckDlg.cpp",
         "MemoryView.cpp",
         "MemoryWindow.cpp",
         "RegisterWindow.cpp",
         "RegisterView.cpp",
         "JitWindow.cpp",
        ]
wxenv = env.Clone()
wxenv.Append(
	CXXFLAGS = [
		'-DUSE_XPM_BITMAPS',
		'-DwxNEEDS_CHARPP'
		],
	LINKFLAGS = [
		'-L/usr/local/lib',
		'-pthread',
		]
	)

wxenv.StaticLibrary("debwx", files, LIBS = [ "common" ])
