# -*- python -*-

Import('env')

if not env['HAVE_WX']:
    Return()

files = [
    "BreakPointDlg.cpp",
    "BreakpointView.cpp",
    "BreakpointWindow.cpp",
    "CodeWindow.cpp",
    "CodeWindowFunctions.cpp",
    "MemoryCheckDlg.cpp",
    "MemoryWindow.cpp",
    "RegisterWindow.cpp",
    "RegisterView.cpp",
    "JitWindow.cpp",
    ]
wxenv = env.Clone()
wxenv.Append(
	CPPDEFINES = [
		'USE_XPM_BITMAPS',
		'wxNEEDS_CHARPP'
		],
	LINKFLAGS = [
		'-pthread',
		]
	)
libs = [
    'common',
	'debugger_ui_util'
]

wxenv.StaticLibrary(env['local_libs'] + "debwx", files, LIBS = libs)
