# -*- python -*-

Import('env')

if not env['HAVE_WX']:
	Return()

files = [
	"BreakpointDlg.cpp",
	"BreakpointView.cpp",
	"BreakpointWindow.cpp",
	"CodeWindow.cpp",
	"CodeWindowFunctions.cpp",
	"DSPDebugWindow.cpp",
	"DSPRegisterView.cpp",
	"MemoryCheckDlg.cpp",
	"MemoryWindow.cpp",
	"RegisterWindow.cpp",
	"RegisterView.cpp",
	"JitWindow.cpp",
	]

env.StaticLibrary(env['local_libs'] + "debwx", files)
