# -*- python -*-

Import('env')

files = [
	'VideoConfig.cpp',
	'GlobalControl.cpp',
	'BPMemory.cpp',
	'CPMemory.cpp',
	'XFMemory.cpp',
	'XFStructs.cpp',
	'BPStructs.cpp',
	'memcpy_amd.cpp',
	'OpcodeDecoding.cpp',
	'TextureDecoder.cpp',
#	'OpenCL/TextureDecoder.cpp',
	'XFMemory.cpp',
	'XFBConvert.cpp',
	'IndexGenerator.cpp',
	'PixelShaderGen.cpp',
	'PixelShaderManager.cpp',
	'VertexShaderGen.cpp',
	'VertexShaderManager.cpp',
	'VertexLoader.cpp',
	'VertexLoader_Color.cpp',
	'VertexLoader_Normal.cpp',
	'VertexLoader_Position.cpp',
	'VertexLoader_TextCoord.cpp',
	'TextureConversionShader.cpp',
	'ImageWrite.cpp',
	'NativeVertexWriter.cpp',
	'Statistics.cpp',
	'Fifo.cpp',
	'VideoState.cpp',
	'Profiler.cpp',
	'OnScreenDisplay.cpp',
	'HiresTextures.cpp',
	]

env_common = env.Clone()
env_common.Append(CXXFLAGS = [ '-fPIC' ])
env_common.StaticLibrary(env['local_libs'] + "videocommon", files)
