.Dd July 17, 2016
.Dt DOLPHIN-EMU-NOGUI 6
.Os
.Sh NAME
.Nm dolphin-emu-nogui
.Nd Nintendo GameCube and Wii emulator
.Sh SYNOPSIS
.Nm dolphin-emu-nogui
.Op Fl hv
.Op Fl e Ar file
.Sh DESCRIPTION
Dolphin is an emulator for two recent Nintendo video game consoles:
the GameCube and the Wii.
It allows PC gamers to enjoy games for these two consoles
in full HD (1080p) with several enhancements:
compatibility with all PC controllers, turbo speed, networked multiplayer,
and even more!
.Pp
.Nm
does not have a graphical user interface.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl e Ar file , Fl Fl exec= Ns Ar file
Load the specified file
.It Fl h , Fl Fl help
Print a help message
.It Fl v , Fl Fl version
Print version and exit
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.dolphin-emu
Default user configuration directory.
.El
.Sh AUTHORS
This manual page was written by Jeremy Newton, but may be distributed freely
using the CC BY license.
