.Dd July 17, 2016
.Dt DOLPHIN-EMU 6
.Os
.Sh NAME
.Nm dolphin-emu
.Nd Nintendo GameCube and Wii emulator
.Sh SYNOPSIS
.Nm dolphin-emu
.Op Fl bdhl
.Op Fl a Ar audio
.Op Fl c Ar str
.Op Fl e Ar file
.Op Fl m Ar file
.Op Fl u Ar path
.Op Fl v Ar video
.Sh DESCRIPTION
Dolphin is an emulator for two recent Nintendo video game consoles:
the GameCube and the Wii.
It allows PC gamers to enjoy games for these two consoles
in full HD (1080p) with several enhancements:
compatibility with all PC controllers, turbo speed, networked multiplayer,
and even more!
.Pp
.Nm
features a graphical user interface made using Qt 5.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a Ar audio , Fl Fl audio_emulation= Ns Ar audio
Low level
.Pq Sy LLE
or high level
.Pq Sy HLE
audio
.It Fl b , Fl Fl batch
Exit Dolphin with emulator
.It Fl c Ar text , Fl Fl confirm= Ns Ar text
Set Confirm on Stop
.It Fl d , Fl Fl debugger
Open the debugger
.It Fl e Ar file , Fl Fl exec= Ns Ar file
Load the specified file
.It Fl h , Fl Fl help
Print a help message
.It Fl l , Fl Fl logger
Open the logger
.Po
.Pa .dol , .elf , .wad , .gcm , .iso
.Pc
.It Fl m Ar file , Fl Fl movie= Ns Ar file
Play a movie file
.It Fl u Ar path , Fl Fl user= Ns Ar path
User folder path
.It Fl v , Fl Fl video_backend= Ns Ar video
OpenGL
.Pq Sy OGL
or
.Sy Software Renderer
video backend
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.dolphin-emu
Default user configuration directory.
.El
.Sh AUTHOR
This manual page was written by Jeremy Newton, but may be distributed freely
using the CC BY license.
