# -*- python -*-

Import('env')
import sys

name = "Plugin_GCPadNew"
padenv = env.Clone()

files = [
	'GCPadNew.cpp',
	'GCPadEmu.cpp',
	]

padenv.Append(
	LIBS = [ 'inputplugincommon', 'inputcommon', 'common' ],
	)

if sys.platform == 'darwin':
	padenv['FRAMEWORKS'] = ['CoreFoundation', 'System', 'Cocoa', 'IOKit' ]

padenv.SharedLibrary(env['plugin_dir']+name, files)
