// Copyright 2010 Dolphin Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

{DIK_A, "A"}, {DIK_B, "B"}, {DIK_C, "C"}, {DIK_D, "D"}, {DIK_E, "E"}, {DIK_F, "F"}, {DIK_G, "G"},
    {DIK_H, "H"}, {DIK_I, "I"}, {DIK_J, "J"}, {DIK_K, "K"}, {DIK_L, "L"}, {DIK_M, "M"},
    {DIK_N, "N"}, {DIK_O, "O"}, {DIK_P, "P"}, {DIK_Q, "Q"}, {DIK_R, "R"}, {DIK_S, "S"},
    {DIK_T, "T"}, {DIK_U, "U"}, {DIK_V, "V"}, {DIK_W, "W"}, {DIK_X, "X"}, {DIK_Y, "Y"},
    {DIK_Z, "Z"}, {DIK_0, "0"}, {DIK_1, "1"}, {DIK_2, "2"}, {DIK_3, "3"}, {DIK_4, "4"},
    {DIK_5, "5"}, {DIK_6, "6"}, {DIK_7, "7"}, {DIK_8, "8"}, {DIK_9, "9"}, {DIK_UP, "Up"},
    {DIK_DOWN, "Down"}, {DIK_LEFT, "Left"}, {DIK_RIGHT, "Right"}, {DIK_ABNT_C1, "ABNT_C1"},
    {DIK_ABNT_C2, "ABNT_C2"}, {DIK_ADD, "ADD"}, {DIK_APOSTROPHE, "'"}, {DIK_APPS, "APPS"},
    {DIK_AT, "AT"}, {DIK_AX, "AX"}, {DIK_BACK, "Backspace"}, {DIK_BACKSLASH, "\\"},
    {DIK_CALCULATOR, "CALCULATOR"}, {DIK_CAPITAL, "CAPITAL"}, {DIK_COLON, ":"},
    {DIK_COMMA, ","}, {DIK_CONVERT, "CONVERT"}, {DIK_DECIMAL, "Numpad ."},
    {DIK_DELETE, "Delete"}, {DIK_DIVIDE, "DIVIDE"}, {DIK_EQUALS, "="}, {DIK_ESCAPE, "Esc"},
    {DIK_F1, "F1"}, {DIK_F2, "F2"}, {DIK_F3, "F3"}, {DIK_F4, "F4"}, {DIK_F5, "F5"}, {DIK_F6, "F6"},
    {DIK_F7, "F7"}, {DIK_F8, "F8"}, {DIK_F9, "F9"}, {DIK_F10, "F10"}, {DIK_F11, "F11"},
    {DIK_F12, "F12"}, {DIK_F13, "F13"}, {DIK_F14, "F14"}, {DIK_F15, "F15"}, {DIK_GRAVE, "`"},
    {DIK_HOME, "Home"}, {DIK_END, "End"}, {DIK_INSERT, "Insert"}, {DIK_KANA, "KANA"},
    {DIK_KANJI, "KANJI"}, {DIK_MAIL, "MAIL"}, {DIK_MEDIASELECT, "MEDIASELECT"},
    {DIK_MEDIASTOP, "MEDIASTOP"}, {DIK_MINUS, "-"}, {DIK_MULTIPLY, "MULTIPLY"},
    {DIK_MUTE, "MUTE"}, {DIK_MYCOMPUTER, "MYCOMPUTER"}, {DIK_NEXTTRACK, "NEXTTRACK"},
    {DIK_NOCONVERT, "NOCONVERT"}, {DIK_NUMLOCK, "Num Lock"}, {DIK_NUMPAD0, "Numpad 0"},
    {DIK_NUMPAD1, "Numpad 1"}, {DIK_NUMPAD2, "Numpad 2"}, {DIK_NUMPAD3, "Numpad 3"},
    {DIK_NUMPAD4, "Numpad 4"}, {DIK_NUMPAD5, "Numpad 5"}, {DIK_NUMPAD6, "Numpad 6"},
    {DIK_NUMPAD7, "Numpad 7"}, {DIK_NUMPAD8, "Numpad 8"}, {DIK_NUMPAD9, "Numpad 9"},
    {DIK_NUMPADCOMMA, "Numpad ,"}, {DIK_NUMPADENTER, "Numpad Enter"},
    {DIK_NUMPADEQUALS, "Numpad ="}, {DIK_OEM_102, "OEM_102"}, {DIK_PAUSE, "Pause"},
    {DIK_PERIOD, "."}, {DIK_PLAYPAUSE, "PLAYPAUSE"}, {DIK_POWER, "POWER"},
    {DIK_PREVTRACK, "PREVTRACK"}, {DIK_PRIOR, "PRIOR"}, {DIK_NEXT, "NEXT"}, {DIK_RETURN, "Enter"},
    {DIK_LBRACKET, "[]"}, {DIK_RBRACKET, "]"}, {DIK_LCONTROL, "LCONTROL"},
    {DIK_RCONTROL, "Right Ctrl"}, {DIK_LMENU, "Left Alt"}, {DIK_RMENU, "Right Alt"}, {DIK_LSHIFT, "Left Shift"},
    {DIK_RSHIFT, "Right Shift"}, {DIK_LWIN, "Left Meta"}, {DIK_RWIN, "Right Meta"}, {DIK_SCROLL, "Scroll Lock"},
    {DIK_SEMICOLON, ";"}, {DIK_SLASH, "/"}, {DIK_SLEEP, "SLEEP"}, {DIK_SPACE, "Space"},
    {DIK_STOP, "STOP"}, {DIK_SUBTRACT, "SUBTRACT"}, {DIK_SYSRQ, "Print Screen"}, {DIK_TAB, "Tab"},
    {DIK_UNDERLINE, "UNDERLINE"}, {DIK_UNLABELED, "UNLABELED"}, {DIK_VOLUMEDOWN, "VOLUMEDOWN"},
    {DIK_VOLUMEUP, "VOLUMEUP"}, {DIK_WAKE, "WAKE"}, {DIK_WEBBACK, "WEBBACK"},
    {DIK_WEBFAVORITES, "WEBFAVORITES"}, {DIK_WEBFORWARD, "WEBFORWARD"}, {DIK_WEBHOME, "WEBHOME"},
    {DIK_WEBREFRESH, "WEBREFRESH"}, {DIK_WEBSEARCH, "WEBSEARCH"}, {DIK_WEBSTOP, "WEBSTOP"},
    {DIK_YEN, "YEN"},
