# -*- python -*-

Import('env')
import sys

name = "Plugin_GCPad"
padenv = env.Clone()

files = [
	'Config.cpp',
	'GCPad.cpp',
	'Rumble.cpp',
	]

if padenv['HAVE_WX']:
    files += [
        'ConfigJoypad.cpp',
        'ConfigBox.cpp',
        ]

padenv.Append(
	LIBS = [ 'inputcommon', 'common', ],
	)

padenv.SharedLibrary(env['plugin_dir']+name, files)
