# -*- python -*-

Import('env')

files = [
    "assemble.cpp",
    "disassemble.cpp",
    "DSPAccelerator.cpp",
    "DSPBreakpoints.cpp",
    "DSPIntCCUtil.cpp",
    "DSPIntExtOps.cpp",
    "DSPHWInterface.cpp",
    "DSPMemoryMap.cpp",
    "DSPStacks.cpp",
    "DSPAnalyzer.cpp",
    "DspIntArithmetic.cpp",
    "DspIntBranch.cpp",
    "DspIntLoadStore.cpp",
    "DspIntMisc.cpp",
    "DspIntMultiplier.cpp",
    "DSPEmitter.cpp",
    "DSPCodeUtil.cpp",
    "LabelMap.cpp",
    "DSPInterpreter.cpp",
    "DSPCore.cpp",
    "DSPTables.cpp",
    "Jit/DSPJitExtOps.cpp",
    "Jit/DSPJitUtil.cpp",
	"Jit/DSPJitMisc.cpp",
    ]

acenv = env.Clone()

acenv.StaticLibrary(env['local_libs'] + 'dspcore', files, LIBS = [ 'common'] )
