# -*- python -*-

Import('env')

files = [
    'AOSoundStream.cpp',
    'aldlist.cpp',
    'AudioCommonConfig.cpp',
    'OpenALStream.cpp',
    'WaveFile.cpp',
    'Mixer.cpp',
    'AudioCommon.cpp',
    ]

env_audiocommon = env.Clone()
env_audiocommon.Append(CXXFLAGS = [ '-fPIC' ])
env_audiocommon.StaticLibrary('audiocommon', files)
