# -*- python -*- 

Import('env')
import sys

if sys.platform == 'darwin':
	output = '../../../../Binary/mac/Plugins/dsphle.so'
else:
	output = '../../../../Binary/linux/Plugins/dsphle.so'

files = [
	'DSPHandler.cpp',
	'MailHandler.cpp',
	'main.cpp',
	'Config.cpp',
	'Globals.cpp',
	'PCHW/AOSoundStream.cpp',
	'PCHW/Mixer.cpp',
        'Debugger/Debugger.cpp',
        'Debugger/PBView.cpp',
        'Logging/Logging.cpp',
	'UCodes/UCode_AX.cpp',
	'UCodes/UCode_CARD.cpp',
	'UCodes/UCode_InitAudioSystem.cpp',
	'UCodes/UCode_Jac.cpp',
	'UCodes/UCode_ROM.cpp',
	'UCodes/UCodes.cpp',
	'UCodes/UCode_Zelda.cpp',
	]

dspenv = env.Clone()
dspenv.Append(
	CXXFLAGS = [ '-fPIC' ],
	LIBS = [ 'common' ],
	)
dspenv.SharedLibrary(output, files)
