name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: cd ./Source/Android/ && chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug          
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/*.apk   # 改为 debug 目录
