.TH DOLPHIN-EMU 6 "March 3, 2016"
.SH NAME
\fBdolphin-emu\fR is an emulator for running GameCube, Wii, and Triforce games on
Windows, Linux, OS X, and recent Android devices.
.SH SYNOPSIS
.B dolphin-emu
[\fB-h\fR] [\fB-d\fR] [\fB-l\fR] [\fB-e \fIROM\fR] [\fB-b\fR] [\fB-V \fIVIDEO\fR] [\fB-A \fIAUDIO\fR]
.SH DESCRIPTION
Dolphin is an emulator for two recent Nintendo video game consoles: the
GameCube and the Wii. It allows PC gamers to enjoy games for these two consoles
in full HD (1080p) with several enhancements: compatibility with all PC
controllers, turbo speed, networked multiplayer, and even more!
.P
\fBdolphin-emu\fR features a graphical user interface made using wxWidgets.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show this help message
.TP
.BR \-d ", " \-\-debugger
Opens the debugger
.TP
.BR \-l ", " \-\-logger
Opens the logger
.TP
.BR \-e ", " \-\-exec =\fIROM\fR
Loads the specified file (\fBDOL,ELF,WAD,GCM,ISO\fR)
.TP
.BR \-b ", " \-\-batch
Exit Dolphin with emulator
.TP
.BR \-V ", " \-\-video_backend =\fIVIDEO\fR
OpenGL (\fBOGL\fR) or \fBSoftware Renderer\fR video backend
.TP
.BR \-A ", " \-\-audio_emulation =\fIAUDIO\fR
Low level (\fBLLE\fR) or high level (\fBHLE\fR) audio
.SH AUTHOR
This manual page was written by Jeremy Newton, but may be distributed freely
using the CC BY license.
